// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdxdTUV8lI8rW9JtZVRAxDvx1qoYq1XBs',
    appId: '1:903008121747:web:6e934105f3fc525ac66e66',
    messagingSenderId: '903008121747',
    projectId: 'note-task-1d26a',
    authDomain: 'note-task-1d26a.firebaseapp.com',
    storageBucket: 'note-task-1d26a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWhNiCuT2uafDKEDNjJFX3e3y-sVgrFu8',
    appId: '1:903008121747:android:df2839f8bf7aba14c66e66',
    messagingSenderId: '903008121747',
    projectId: 'note-task-1d26a',
    storageBucket: 'note-task-1d26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpPXx7VORTHRsZxNjCkyj-_Bb09hIbIh0',
    appId: '1:903008121747:ios:051d9d03189387e9c66e66',
    messagingSenderId: '903008121747',
    projectId: 'note-task-1d26a',
    storageBucket: 'note-task-1d26a.firebasestorage.app',
    iosBundleId: 'dev.zayan.noteTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpPXx7VORTHRsZxNjCkyj-_Bb09hIbIh0',
    appId: '1:903008121747:ios:051d9d03189387e9c66e66',
    messagingSenderId: '903008121747',
    projectId: 'note-task-1d26a',
    storageBucket: 'note-task-1d26a.firebasestorage.app',
    iosBundleId: 'dev.zayan.noteTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdxdTUV8lI8rW9JtZVRAxDvx1qoYq1XBs',
    appId: '1:903008121747:web:7bd80394151fb4cdc66e66',
    messagingSenderId: '903008121747',
    projectId: 'note-task-1d26a',
    authDomain: 'note-task-1d26a.firebaseapp.com',
    storageBucket: 'note-task-1d26a.firebasestorage.app',
  );
}
